### PR TITLE
New smart multiple new submit modal for #60

### PR DESCRIPTION
**Pull request by TheRolfFR**
Created smart new contribution modal with expansion panels, where it clones the content of the opened form when clicking new. If no form opened, creates a new empty form:

image

@Pomi108 what do you think? It's for issue #60

### CODE REVIEW

**Comment by Pomi108** [comment]
This looks good, but i'm not entirely sure how it's supposed to work?

**Comment by TheRolfFR** [comment]
Well, when clicking on add manually, you get multiple contribution form, and you can clone forms when one is opened and you can eventually submit all of them at once

**Review by Lorenzo0310200 — APPROVED** [review]

**Comment by TheRolfFR** [comment]
I propose that we close this PR because we will use new technologies for the website.
Thus, it is useless to persevere with it unless you have a very great need.

**Comment by TheRolfFR** [comment]
I made huge improvements increasing the style:
image

**Comment by Pomi108** [comment]
YES but i also kind of want to see this in action, could you record a video? :eyes:

**Comment by TheRolfFR** [comment]
Here you go (I couldn't get a preview sorry,click the link): [continuation.webm](https://github.com/Faithful-Resource-Pack/App/assets/18086786/e614ef9f-b494-48ad-af8b-76f6c814436a)

**Comment by Pomi108** [comment]
Looks good to me! This is gonna be very useful.
A feature I'd also appreciate would be the ability to set a range of IDs for a contribution to be added to, so I don't have to do it manually for each one
Just an idea

**Comment by TheRolfFR** [comment]
More modifications with ids range:
image

**Comment by Pomi108** [comment]
Can you replace the arrow `→` with an en dash `–`? It's more appropriate

**Comment by TheRolfFR** [comment]
I am also improving the contribution page layout
Before:
image
After:
image

**Comment by Pomi108** [comment]
looks good

**Review by 3vorp — APPROVED** [review]

**Pull request merged**
